# Do hyperparameter setting here
vit_linear:
    lr: 0.001
    wd: 0.01
    epochs: 100
    optimizer: 'sgd'
    scheduler: 'multi_step'
    momentum: 0.99
    net_class: ViTLinear
    batch_size: 32

vpt_deep:
    lr: 0.01
    wd: 0.01
    epochs: 100
    optimizer: 'sgd'
    scheduler: 'multi_step'
    momentum: 0.9
    net_class: VPTDeep
    batch_size: 64
    prompt_len: 10

full_finetune:
    lr: 1e-5
    wd: 0.05
    epochs: 50
    optimizer: 'adamw'
    scheduler: 'warmup_cosine'
    net_class: ViTLinear
    batch_size: 32